# Generated by Django 4.2.16 on 2024-09-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(default=0)),
                ('role_name', models.CharField(choices=[('Research Staff Member', 'Research Staff Member'), ('Order Manager', 'Order Manager'), ('Stock Manager', 'Stock Manager'), ('Higher Approver', 'Higher Approver'), ('Admin', 'Admin'), ('Supervisor', 'Supervisor')], default='Research Staff Member', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furc.userrole')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
