# Generated by Django 4.2.16 on 2024-09-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role_name',
            field=models.CharField(choices=[('Research Staff Member', 'Research Staff Member'), ('Admin', 'Admin'), ('Higher Approver', 'Higher Approver'), ('Stock Manager', 'Stock Manager'), ('Order Manager', 'Order Manager'), ('Supervisor', 'Supervisor')], default='Research Staff Member', max_length=100),
        ),
    ]
