# Generated by Django 4.2.16 on 2024-09-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
