# Generated by Django 4.2.16 on 2024-09-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0002_myuser_is_staff_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role_name',
            field=models.CharField(choices=[('Stock Manager', 'Stock Manager'), ('Higher Approver', 'Higher Approver'), ('Order Manager', 'Order Manager'), ('Research Staff Member', 'Research Staff Member'), ('Supervisor', 'Supervisor'), ('Admin', 'Admin')], default='Research Staff Member', max_length=100),
        ),
    ]
