# Generated by Django 4.2.16 on 2024-09-22 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0002_alter_userrole_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('institute_id', models.IntegerField(primary_key=True, serialize=False)),
                ('institute_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchCenter',
            fields=[
                ('center_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=255)),
                ('institute_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='furc.institute')),
            ],
        ),
    ]
