# Generated by Django 4.2.16 on 2024-09-22 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('furc', '0003_institute_researchcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('storage_location_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('storage_location_name', models.CharField(max_length=50)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('Laboratory', 'ResearchCenter', 'Institute')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('lab_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=50)),
                ('center_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='furc.researchcenter')),
            ],
        ),
    ]
