# Generated by Django 4.2.16 on 2024-09-22 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('furc', '0004_storagelocation_laboratory'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('laboratory', 'researchcenter', 'institute')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
