# Generated by Django 4.2.16 on 2024-09-22 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0006_alter_storagelocation_object_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagelocation',
            old_name='object_id',
            new_name='location_id',
        ),
    ]
