# Generated by Django 4.2.16 on 2024-09-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0008_storagelevel_riskcategory_chemical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('exp_name', models.CharField(max_length=100)),
                ('exp_procedure', models.FileField(upload_to='<django.db.models.fields.CharField>/exp_procedure')),
                ('risk_assessment', models.FileField(upload_to='<django.db.models.fields.CharField>/risk_assessment')),
                ('order_date', models.DateField(auto_now=True)),
                ('order_status', models.CharField(choices=[('Stored', 'Stored'), ('Delivered', 'Delivered'), ('Pending approval', 'Pending approval'), ('Closed', 'Closed'), ('rejected', 'rejected'), ('Approved by supervisor', 'Approved by supervisor'), ('Requested', 'Requested'), ('Approved by higher', 'Approved by higher'), ('Received', 'Received'), ('Order in progress', 'Order in progress'), ('Ordered', 'Ordered'), ('Pending higher approval', 'Pending higher approval')], default='Requested', max_length=30)),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furc.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_amount', models.IntegerField(default=1)),
                ('uom', models.CharField(default='ml', max_length=10)),
                ('chemical_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furc.chemical')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furc.order')),
            ],
        ),
    ]
