# Generated by Django 4.2.16 on 2024-09-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0009_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('Pending higher approval', 'Pending higher approval'), ('Order in progress', 'Order in progress'), ('Delivered', 'Delivered'), ('Requested', 'Requested'), ('Approved by higher', 'Approved by higher'), ('Approved by supervisor', 'Approved by supervisor'), ('Stored', 'Stored'), ('Closed', 'Closed'), ('Pending approval', 'Pending approval'), ('Received', 'Received'), ('Ordered', 'Ordered')], default='Requested', max_length=30),
        ),
    ]
