# Generated by Django 4.2.16 on 2024-09-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0011_alter_order_order_date_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exp_procedure',
            field=models.FileField(upload_to='order/exp_procedure'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Approved by supervisor', 'Approved by supervisor'), ('Ordered', 'Ordered'), ('rejected', 'rejected'), ('Pending approval', 'Pending approval'), ('Order in progress', 'Order in progress'), ('Stored', 'Stored'), ('Approved by higher', 'Approved by higher'), ('Pending higher approval', 'Pending higher approval'), ('Requested', 'Requested'), ('Closed', 'Closed'), ('Delivered', 'Delivered'), ('Received', 'Received')], default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='risk_assessment',
            field=models.FileField(upload_to='order/risk_assessment'),
        ),
    ]
