# Generated by Django 4.2.16 on 2024-09-23 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0012_alter_order_exp_procedure_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stock_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('Order in progress', 'Order in progress'), ('Stored', 'Stored'), ('Received', 'Received'), ('Ordered', 'Ordered'), ('Pending higher approval', 'Pending higher approval'), ('Requested', 'Requested'), ('Pending approval', 'Pending approval'), ('Closed', 'Closed'), ('Delivered', 'Delivered'), ('Approved by higher', 'Approved by higher'), ('Approved by supervisor', 'Approved by supervisor')], default='Requested', max_length=30),
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_stock', models.IntegerField(default=0)),
                ('Current_stock', models.IntegerField(default=0)),
                ('uom', models.CharField(default='ml', max_length=10)),
                ('disposal_date', models.DateField()),
                ('disposal_status', models.CharField(choices=[('NOT YET', 'Not yet'), ('DISPOSED', 'Disposed')], default='Not yet', max_length=20)),
                ('chemical_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furc.chemical')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furc.stock')),
                ('storage_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furc.storagelevel')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furc.storagelocation')),
            ],
        ),
    ]
