# Generated by Django 4.2.16 on 2024-09-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0013_stock_alter_order_order_status_stockitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order in progress', 'Order in progress'), ('Pending approval', 'Pending approval'), ('Ordered', 'Ordered'), ('Delivered', 'Delivered'), ('Requested', 'Requested'), ('Received', 'Received'), ('rejected', 'rejected'), ('Approved by higher', 'Approved by higher'), ('Pending higher approval', 'Pending higher approval'), ('Closed', 'Closed'), ('Approved by supervisor', 'Approved by supervisor'), ('Stored', 'Stored')], default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='disposal_status',
            field=models.CharField(choices=[('DISPOSED', 'Disposed'), ('NOT YET', 'Not yet')], default='Not yet', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
