# Generated by Django 4.2.16 on 2024-09-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0014_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending higher approval', 'Pending higher approval'), ('Approved by higher', 'Approved by higher'), ('Delivered', 'Delivered'), ('rejected', 'rejected'), ('Stored', 'Stored'), ('Received', 'Received'), ('Pending approval', 'Pending approval'), ('Requested', 'Requested'), ('Approved by supervisor', 'Approved by supervisor'), ('Ordered', 'Ordered'), ('Closed', 'Closed'), ('Order in progress', 'Order in progress')], default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='disposal_status',
            field=models.CharField(choices=[('NOT YET', 'Not yet'), ('DISPOSED', 'Disposed')], default='Not yet', max_length=20),
        ),
    ]
