# Generated by Django 4.2.16 on 2024-09-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0015_rename_user_name_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending approval', 'Pending approval'), ('Received', 'Received'), ('Ordered', 'Ordered'), ('Closed', 'Closed'), ('Order in progress', 'Order in progress'), ('Pending higher approval', 'Pending higher approval'), ('Delivered', 'Delivered'), ('Stored', 'Stored'), ('Requested', 'Requested'), ('Approved by supervisor', 'Approved by supervisor'), ('Approved by higher', 'Approved by higher'), ('rejected', 'rejected')], default='Requested', max_length=30),
        ),
    ]
