# Generated by Django 4.2.16 on 2024-09-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0016_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='uom',
            field=models.CharField(choices=[('g', 'g'), ('ml', 'ml')], default='g', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Approved by supervisor', 'Approved by supervisor'), ('rejected', 'rejected'), ('Order in progress', 'Order in progress'), ('Received', 'Received'), ('Delivered', 'Delivered'), ('Stored', 'Stored'), ('Closed', 'Closed'), ('Requested', 'Requested'), ('Pending approval', 'Pending approval'), ('Approved by higher', 'Approved by higher'), ('Ordered', 'Ordered'), ('Pending higher approval', 'Pending higher approval')], default='Requested', max_length=30),
        ),
    ]
