# Generated by Django 4.2.16 on 2024-09-30 03:28

from django.db import migrations, models
import furc.models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0017_chemical_uom_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='uom',
            field=models.CharField(choices=[('ml', 'ml'), ('g', 'g')], default='g', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='exp_procedure',
            field=models.FileField(upload_to=furc.models.custom_file_upload_path_exp),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending approval', 'Pending approval'), ('Requested', 'Requested'), ('Approved by supervisor', 'Approved by supervisor'), ('rejected', 'rejected'), ('Received', 'Received'), ('Closed', 'Closed'), ('Delivered', 'Delivered'), ('Stored', 'Stored'), ('Pending higher approval', 'Pending higher approval'), ('Order in progress', 'Order in progress'), ('Ordered', 'Ordered'), ('Approved by higher', 'Approved by higher')], default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='risk_assessment',
            field=models.FileField(upload_to=furc.models.custom_file_upload_path_risk),
        ),
    ]
