# Generated by Django 4.2.16 on 2024-09-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0018_alter_chemical_uom_alter_order_exp_procedure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Pending higher approval', 'Pending higher approval'), ('Received', 'Received'), ('Delivered', 'Delivered'), ('Order in progress', 'Order in progress'), ('Requested', 'Requested'), ('Pending approval', 'Pending approval'), ('Approved by supervisor', 'Approved by supervisor'), ('Ordered', 'Ordered'), ('Approved by higher', 'Approved by higher'), ('Stored', 'Stored'), ('rejected', 'rejected')], default='Requested', max_length=30),
        ),
    ]
