# Generated by Django 4.2.16 on 2024-09-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0019_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='uom',
            field=models.CharField(choices=[('g', 'g'), ('ml', 'ml')], default='g', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Stored', 'Stored'), ('Closed', 'Closed'), ('Received', 'Received'), ('Delivered', 'Delivered'), ('Ordered', 'Ordered'), ('Approved by supervisor', 'Approved by supervisor'), ('Order in progress', 'Order in progress'), ('Pending approval', 'Pending approval'), ('Approved by higher', 'Approved by higher'), ('rejected', 'rejected'), ('Pending higher approval', 'Pending higher approval')], default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='disposal_status',
            field=models.CharField(choices=[('DISPOSED', 'Disposed'), ('NOT YET', 'Not yet')], default='Not yet', max_length=20),
        ),
    ]
