# Generated by Django 4.2.16 on 2024-09-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0020_alter_chemical_uom_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Received', 'Received'), ('Delivered', 'Delivered'), ('Stored', 'Stored'), ('Approved by higher', 'Approved by higher'), ('Closed', 'Closed'), ('Ordered', 'Ordered'), ('Rejected by supervisor', 'Rejected by supervisor'), ('Pending approval', 'Pending approval'), ('Pending higher approval', 'Pending higher approval'), ('Approved by supervisor', 'Approved by supervisor'), ('Rejected by higher', 'Rejected by higher'), ('Requested', 'Requested'), ('Order in progress', 'Order in progress')], default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='disposal_status',
            field=models.CharField(choices=[('NOT YET', 'Not yet'), ('DISPOSED', 'Disposed')], default='Not yet', max_length=20),
        ),
    ]
