# Generated by Django 4.2.16 on 2024-10-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0021_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='max_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order in progress', 'Order in progress'), ('Ordered', 'Ordered'), ('Closed', 'Closed'), ('Requested', 'Requested'), ('Rejected by higher', 'Rejected by higher'), ('Approved by higher', 'Approved by higher'), ('Pending approval', 'Pending approval'), ('Stored', 'Stored'), ('Rejected by supervisor', 'Rejected by supervisor'), ('Pending higher approval', 'Pending higher approval'), ('Received', 'Received'), ('Approved by supervisor', 'Approved by supervisor'), ('Delivered', 'Delivered')], default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='disposal_status',
            field=models.CharField(choices=[('DISPOSED', 'Disposed'), ('NOT YET', 'Not yet')], default='Not yet', max_length=20),
        ),
    ]
