# Generated by Django 4.2.16 on 2024-10-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0022_storagelocation_max_limit_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order in progress', 'Order in progress'), ('Approved by supervisor', 'Approved by supervisor'), ('Delivered', 'Delivered'), ('Stored', 'Stored'), ('Pending higher approval', 'Pending higher approval'), ('Closed', 'Closed'), ('Received', 'Received'), ('Ordered', 'Ordered'), ('Rejected by supervisor', 'Rejected by supervisor'), ('Rejected by higher', 'Rejected by higher'), ('Pending approval', 'Pending approval'), ('Requested', 'Requested'), ('Approved by higher', 'Approved by higher')], default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='disposal_status',
            field=models.CharField(choices=[('NOT YET', 'Not yet'), ('DISPOSED', 'Disposed')], default='Not yet', max_length=20),
        ),
    ]
