# Generated by Django 4.2.16 on 2024-10-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0023_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Rejected by supervisor', 'Rejected by supervisor'), ('Closed', 'Closed'), ('Approved by higher', 'Approved by higher'), ('Order in progress', 'Order in progress'), ('Pending higher approval', 'Pending higher approval'), ('Rejected by higher', 'Rejected by higher'), ('Approved by supervisor', 'Approved by supervisor'), ('Received', 'Received'), ('Requested', 'Requested'), ('Delivered', 'Delivered'), ('Pending approval', 'Pending approval'), ('Stored', 'Stored'), ('Ordered', 'Ordered')], default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='disposal_status',
            field=models.CharField(choices=[('DISPOSED', 'Disposed'), ('NOT YET', 'Not yet')], default='Not yet', max_length=20),
        ),
    ]
