# Generated by Django 4.2.16 on 2024-10-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0024_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Rejected', 'Rejected'), ('Approved by supervisor', 'Approved by supervisor'), ('Order in progress', 'Order in progress'), ('Approved by higher', 'Approved by higher'), ('Ordered', 'Ordered'), ('Closed', 'Closed'), ('Rejected by supervisor', 'Rejected by supervisor'), ('Pending higher approval', 'Pending higher approval'), ('Rejected by higher', 'Rejected by higher'), ('Pending approval', 'Pending approval'), ('Requested', 'Requested'), ('Received', 'Received'), ('Stored', 'Stored')], default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='disposal_status',
            field=models.CharField(choices=[('NOT YET', 'Not yet'), ('DISPOSED', 'Disposed')], default='Not yet', max_length=20),
        ),
    ]
