name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Option 1: Fixing permissions and forcing Jekyll to create cache
    - name: Build the site with Jekyll in Docker (Fixing Cache Permissions)
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "mkdir -p /srv/jekyll/.jekyll-cache && chmod -R 777 /srv/jekyll/.jekyll-cache && jekyll build --future"

    # Option 2: Disabling Jekyll cache to avoid permissions issues
    # Uncomment if you want to disable the cache instead of setting permissions
    # - name: Build the site without Jekyll cache
    #   run: |
    #     docker run \
    #     -v ${{ github.workspace }}:/srv/jekyll \
    #     -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
    #     jekyll/builder:latest /bin/bash -c "jekyll build --no-cache --future"
