name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Option 1: Setting proper permissions inside the container
    - name: Build the site in the Jekyll builder container with fixed permissions
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll/.jekyll-cache && jekyll build --future"

    # Option 2: Running as the same user as on the host machine
    # Uncomment this block if you'd like to run the container as a specific user
    # - name: Build the site in the Jekyll builder container as a specific user
    #   run: |
    #     docker run \
    #     -v ${{ github.workspace }}:/srv/jekyll \
    #     -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
    #     --user $(id -u):$(id -g) \
    #     jekyll/builder:latest /bin/bash -c "jekyll build --future"

    # Option 3: Disabling caching to avoid permission issues
    # Uncomment this block if you'd like to disable Jekyll caching
    # - name: Build the site in the Jekyll builder container without caching
    #   run: |
    #     docker run \
    #     -v ${{ github.workspace }}:/srv/jekyll \
    #     -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
    #     jekyll/builder:latest /bin/bash -c "jekyll build --no-cache --future"
